// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-seasons.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function resolveSeasonId(supabase, seasonId) {
  if (seasonId) return seasonId;
  const { data, error } = await supabase.from("seasons").select("id").eq("status", "active").order("created_at", { ascending: false }).limit(1).maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("\u0644\u0627 \u064A\u0648\u062C\u062F \u0645\u0648\u0633\u0645 \u0646\u0634\u0637. \u0645\u0631\u0651\u0631 season_id \u0635\u0631\u0627\u062D\u0629\u064B.");
  return data.id;
}
function textResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-seasons.ts
var list_seasons_default = defineTool({
  name: "list_seasons",
  title: "List seasons",
  description: "List the olive mill seasons owned by the signed-in user, including pricing settings.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("seasons").select("id,name,status,start_date,end_date,return_percent,oil_buy_price,oil_sell_price,cash_return_cost,plastic_container_price,metal_container_price").order("created_at", { ascending: false });
    if (error) return errorResult(error.message);
    return textResult({ seasons: data ?? [] });
  }
});

// src/lib/mcp/tools/list-queue.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_queue_default = defineTool2({
  name: "list_queue",
  title: "List queue",
  description: "List customers in the mill queue for a season (waiting, processing, completed).",
  inputSchema: {
    season_id: z.string().uuid().optional().describe("Season id. Defaults to the active season."),
    status: z.enum(["waiting", "processing", "completed"]).optional().describe("Filter by queue status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ season_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    try {
      const seasonId = await resolveSeasonId(supabase, season_id);
      let query = supabase.from("queue").select("id,name,bags,phone,notes,position,status,created_at").eq("season_id", seasonId).order("position", { ascending: true });
      if (status) query = query.eq("status", status);
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return textResult({ season_id: seasonId, queue: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/add-to-queue.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var add_to_queue_default = defineTool3({
  name: "add_to_queue",
  title: "Add customer to queue",
  description: "Add a customer to the end of the mill queue for a season.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Customer name."),
    bags: z2.number().int().min(1).describe("Number of olive bags."),
    phone: z2.string().trim().optional(),
    notes: z2.string().trim().optional(),
    season_id: z2.string().uuid().optional().describe("Season id. Defaults to the active season.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, bags, phone, notes, season_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    try {
      const seasonId = await resolveSeasonId(supabase, season_id);
      const { data, error } = await supabase.from("queue").insert({
        user_id: ctx.getUserId(),
        season_id: seasonId,
        name,
        bags,
        phone: phone || null,
        notes: notes || null,
        status: "waiting"
      }).select().single();
      if (error) return errorResult(error.message);
      return textResult({ entry: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/update-queue-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var update_queue_status_default = defineTool4({
  name: "update_queue_status",
  title: "Update queue status",
  description: "Change a queue entry's status to waiting, processing, or completed.",
  inputSchema: {
    queue_id: z3.string().uuid().describe("Queue entry id."),
    status: z3.enum(["waiting", "processing", "completed"])
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ queue_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("queue").update({ status }).eq("id", queue_id).select().maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Queue entry not found.");
    return textResult({ entry: data });
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_customers_default = defineTool5({
  name: "list_customers",
  title: "List customers",
  description: "List or search customers of a season by name.",
  inputSchema: {
    search: z4.string().trim().optional().describe("Filter by name (partial match)."),
    season_id: z4.string().uuid().optional().describe("Season id. Defaults to the active season."),
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, season_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    try {
      const seasonId = await resolveSeasonId(supabase, season_id);
      let query = supabase.from("customers").select("id,name,phone,created_at").eq("season_id", seasonId).order("created_at", { ascending: false }).limit(limit ?? 50);
      if (search) query = query.ilike("name", `%${search}%`);
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return textResult({ season_id: seasonId, customers: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_invoices_default = defineTool6({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices for a season, newest first.",
  inputSchema: {
    season_id: z5.string().uuid().optional().describe("Season id. Defaults to the active season."),
    limit: z5.number().int().min(1).max(200).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ season_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    try {
      const seasonId = await resolveSeasonId(supabase, season_id);
      const { data, error } = await supabase.from("invoices").select("id,customer_name,oil_produced,oil_amount,cash_amount,payment_type,container_type,container_count,total_display,created_at").eq("season_id", seasonId).order("created_at", { ascending: false }).limit(limit ?? 25);
      if (error) return errorResult(error.message);
      return textResult({ season_id: seasonId, invoices: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/get-inventory.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var get_inventory_default = defineTool7({
  name: "get_inventory",
  title: "Get inventory",
  description: "Get the current oil (kg) and cash (\u20AA) balances for a season.",
  inputSchema: {
    season_id: z6.string().uuid().optional().describe("Season id. Defaults to the active season.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ season_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    try {
      const seasonId = await resolveSeasonId(supabase, season_id);
      const { data, error } = await supabase.from("inventory").select("total_oil,total_cash,updated_at").eq("season_id", seasonId).maybeSingle();
      if (error) return errorResult(error.message);
      return textResult({
        season_id: seasonId,
        total_oil: data?.total_oil ?? 0,
        total_cash: data?.total_cash ?? 0,
        updated_at: data?.updated_at ?? null
      });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/add-expense.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var add_expense_default = defineTool8({
  name: "add_expense",
  title: "Add expense",
  description: "Record an expense for a season.",
  inputSchema: {
    amount: z7.number().positive().describe("Amount in shekels."),
    category: z7.string().trim().min(1).describe("Expense category."),
    description: z7.string().trim().optional(),
    season_id: z7.string().uuid().optional().describe("Season id. Defaults to the active season.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amount, category, description, season_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    try {
      const seasonId = await resolveSeasonId(supabase, season_id);
      const { data, error } = await supabase.from("expenses").insert({
        user_id: ctx.getUserId(),
        season_id: seasonId,
        amount,
        category,
        description: description || null
      }).select().single();
      if (error) return errorResult(error.message);
      return textResult({ expense: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var list_expenses_default = defineTool9({
  name: "list_expenses",
  title: "List expenses",
  description: "List expenses recorded for a season, newest first.",
  inputSchema: {
    season_id: z8.string().uuid().optional().describe("Season id. Defaults to the active season."),
    limit: z8.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ season_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    try {
      const seasonId = await resolveSeasonId(supabase, season_id);
      const { data, error } = await supabase.from("expenses").select("id,amount,category,description,created_at").eq("season_id", seasonId).order("created_at", { ascending: false }).limit(limit ?? 50);
      if (error) return errorResult(error.message);
      return textResult({ season_id: seasonId, expenses: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "cfrxehfzrjbzxqgxpgcv";
var mcp_default = defineMcp({
  name: "olive-flow-manager",
  title: "olive-flow-manager",
  version: "0.1.0",
  instructions: "Tools for the olive mill manager app. Read and manage the mill queue, customers, invoices, expenses, and oil/cash inventory for the signed-in user's seasons. Most tools default to the user's active season when season_id is omitted.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_seasons_default,
    list_queue_default,
    add_to_queue_default,
    update_queue_status_default,
    list_customers_default,
    list_invoices_default,
    get_inventory_default,
    add_expense_default,
    list_expenses_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
